IF OBJECT_ID ('TRG_UPD_GEN_Queue') IS NOT NULL 
BEGIN
	DROP TRIGGER [dbo].[TRG_UPD_GEN_Queue]
END
GO
/****** Object:  Trigger [dbo].[TRG_UPD_GEN_Queue]    Script Date: 8/17/2017 3:16:59 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE TRIGGER [dbo].[TRG_UPD_GEN_Queue]
  ON [dbo].[GEN_Queue]
  AFTER UPDATE,INSERT
  AS

IF EXISTS(SELECT * FROM INSERTED)
INSERT INTO [dbo].[GEN_QueueHistory]
            (GEN_QueueRef
			,BusinessSegmentLkup
			,WorkBasketLkup
			,DiscrepancyCategoryLkup
			,DiscrepancyTypeLkup
			,StartDate
			,StartDateId
			,EndDate
			,EndDateId
			,AssignedToRef
			,UTCAssignedOn
			,UTCAssignedOnId
			,UTCAssignedOnYear
			,UTCAssignedOnMonth
			,UTCAssignedOnDay
			,CSTAssignedOn
			,CSTAssignedOnId
			,CSTAssignedOnYear
			,CSTAssignedOnMonth
			,CSTAssignedOnDay
			,PreviousAssignedToRef
			,LockedByRef
			,UTCLockedOn
			,UTCLockedOnId
			,UTCLockedOnYear
			,UTCLockedOnMonth
			,UTCLockedOnDay
			,CSTLockedOn
			,CSTLockedOnId
			,CSTLockedOnYear
			,CSTLockedOnMonth
			,CSTLockedOnDay
			,MostRecentActionLkup
			,MostRecentWorkQueueLkup
			,MostRecentStatusLkup
			,PreviousWorkQueueLkup
			,PreviousAuditWorkQueueLkup
			,SourceSystemLkup
			,SourceSystemId
			,DiscrepancySourceLkup
			,DiscrepancyReceiptDate
			,DiscrepancyReceiptDateId
			,ComplianceStartDate
			,ComplianceStartDateId
			,DisenrollmentDate
			,Aging
			,DiscrepancyStartDate
			,DiscrepancyStartDateId
			,DiscrepancyEndDate
			,DiscrepancyEndDateId
			,MemberSCCCode
			,PDPAutoEnrolleeInd
			,ReferencedEligibilityCaseInd
			,ReferencedSCCCaseInd
			,FileTypeLkup
			,ODMDocID
			,ODMAddressLink
			,UndeliveredAddress1
			,UndeliveredAddress2
			,UndeliveredCity
			,UndeliveredState
			,UndeliveredZip
			,COAOldAddress1
			,COAOldAddress2
			,COAOldCity
			,COAOldState
			,COAOldZip
			,COANewAddress1
			,COANewAddress2
			,COANewCity
			,COANewState
			,COANewZip
			,MemberID
			,MemberCurrentHICN
			,GPSHouseholdID
			,MemberFirstName
			,MemberMiddleName
			,MemberLastName
			,MemberContractIDLkup
			,MemberPBPLkup
			,MemberLOBLkup
			,MemberVerifiedState
			,MemberVerifiedCountyCode
			,MemberDOB
			,MemberGenderLkup
			,EligGPSContractIDLkup
			,EligGPSPBPLkup
			,EligGPSSCCCode
			,EligGPSCurrentHICN
			,EligGPSInsuredPlanEffectiveDate
			,EligGPSInsuredPlanEffectiveDateId
			,EligGPSInsuredPlanTermDate
			,EligGPSInsuredPlanTermDateId
			,EligGPSLOBLkup
			,EligGPSMemberDOB
			,EligGPSMemberDOBId
			,EligGPSGenderLkup
			,EligMMRContractIDLkup
			,EligMMRPBPLkup
			,EligMMRSCCCode
			,EligMMRCurrentHICN
			,EligMMRPaymentAdjustmentStartDate
			,EligMMRPaymentAdjustmentStartDateId
			,EligMMRPaymentAdjustmentEndDate
			,EligMMRPaymentAdjustmentEndDateId
			,EligMMRPaymentMonth
			,EligMMRDOB
			,EligMMRDOBId
			,EligMMRGenderLkup
			,EligOOAFlagLkup
			,RPRRequestedEffectiveDate
			,RPRRequestedEffectiveDateId
			,RPRActionRequestedLkup
			,RPROtherActionRequested
			,RPRSupervisorOrRequesterRef
			,RPRReasonforRequest
			,RPRTaskPerformedLkup
			,RPROtherTaskPerformed
			,RPRCTMMember
			,RPRCTMNumber
			,RPREGHPMember
			,RPREmployerID
			,SCCRPRRequested
			,SCCRPRRequestedZip
			,SCCRPRRequstedSubmissionDate
			,SCCRPRRequstedSubmissionDateId
			,SCCRPREffectiveStartDate
			,SCCRPREffectiveStartDateId
			,SCCRPREffectiveEndDate
			,SCCRPREffectiveEndDateId
			,IsCasePended
			,PendedbyRef
			,UTCPendedOn
			,UTCPendedOnId
			,UTCPendedOnYear
			,UTCPendedOnMonth
			,UTCPendedOnDay
			,CSTPendedOn
			,CSTPendedOnId
			,CSTPendedOnYear
			,CSTPendedOnMonth
			,CSTPendedOnDay
			,IsCaseResolved
			,ResolvedByRef
			,UTCResolvedOn
			,UTCResolvedOnId
			,UTCResolvedOnYear
			,UTCResolvedOnMonth
			,UTCResolvedOnDay
			,CSTResolvedOn
			,CSTResolvedOnId
			,CSTResolvedOnYear
			,CSTResolvedOnMonth
			,CSTResolvedOnDay
			,PeerAuditCompletedDate
			,PeerAuditCompletedDateId
			,IsParentCase
			,IsChildCase
			,ParentQueueRef
			,IsActive
			,UTCCreatedOn
			,UTCCreatedOnId
			,UTCCreatedOnYear
			,UTCCreatedOnMonth
			,UTCCreatedOnDay
			,CSTCreatedOn
			,CSTCreatedOnId
			,CSTCreatedOnYear
			,CSTCreatedOnMonth
			,CSTCreatedOnDay
			,CreatedByRef
			,UTCLastUpdatedOn
			,UTCLastUpdatedOnId
			,UTCLastUpdatedOnYear
			,UTCLastUpdatedOnMonth
			,UTCLastUpdatedOnDay
			,CSTLastUpdatedOn
			,CSTLastUpdatedOnId
			,CSTLastUpdatedOnYear
			,CSTLastUpdatedOnMonth
			,CSTLastUpdatedOnDay
			,LastUpdatedByRef
			,UTCHistoryCreatedOn
			,HistoryCreatedByRef
			,GEN_ManageCasesRef
			,MemberDOBId
			,TRCLkup
			,IsExtendTrackingRequired
			,MIIMReferenceId
			,IsMARxAddressCompleted
			,IsAddressScrubCompleted
			,RPRCategoryLkup
			,IsRestricted
			,OOALetterStatusLkup
			,CMSTransactionStatusLkup
			,IsNOTMacroProcessed
			,IsTRC155MacroProcessed
			,IsFTTMacroProcessed
			,NOTMacroStatusLkup
			,NOTMacroUpdatedOn
			,NOTMacroUpdatedByRef
			,TRC155MacroStatusLkup
			,TRC155MacroUpdatedOn
			,TRC155MacroUpdatedByRef
			,FTTMacroStatusLkup
			,FTTMacroUpdatedOn
			,FTTMacroUpdatedByRef
			,MemberMedicareId
			,ERNCaseID)
     SELECT			
			GEN_QueueId
			,BusinessSegmentLkup
			,WorkBasketLkup
			,DiscrepancyCategoryLkup
			,DiscrepancyTypeLkup
			,StartDate
			,StartDateId
			,EndDate
			,EndDateId
			,AssignedToRef
			,UTCAssignedOn
			,UTCAssignedOnId
			,UTCAssignedOnYear
			,UTCAssignedOnMonth
			,UTCAssignedOnDay
			,CSTAssignedOn
			,CSTAssignedOnId
			,CSTAssignedOnYear
			,CSTAssignedOnMonth
			,CSTAssignedOnDay
			,PreviousAssignedToRef
			,LockedByRef
			,UTCLockedOn
			,UTCLockedOnId
			,UTCLockedOnYear
			,UTCLockedOnMonth
			,UTCLockedOnDay
			,CSTLockedOn
			,CSTLockedOnId
			,CSTLockedOnYear
			,CSTLockedOnMonth
			,CSTLockedOnDay
			,MostRecentActionLkup
			,MostRecentWorkQueueLkup
			,MostRecentStatusLkup
			,PreviousWorkQueueLkup
			,PreviousAuditWorkQueueLkup
			,SourceSystemLkup
			,SourceSystemId
			,DiscrepancySourceLkup
			,DiscrepancyReceiptDate
			,DiscrepancyReceiptDateId
			,ComplianceStartDate
			,ComplianceStartDateId
			,DisenrollmentDate
			,Aging
			,DiscrepancyStartDate
			,DiscrepancyStartDateId
			,DiscrepancyEndDate
			,DiscrepancyEndDateId
			,MemberSCCCode
			,PDPAutoEnrolleeInd
			,ReferencedEligibilityCaseInd
			,ReferencedSCCCaseInd
			,FileTypeLkup
			,ODMDocID
			,ODMAddressLink
			,UndeliveredAddress1
			,UndeliveredAddress2
			,UndeliveredCity
			,UndeliveredState
			,UndeliveredZip
			,COAOldAddress1
			,COAOldAddress2
			,COAOldCity
			,COAOldState
			,COAOldZip
			,COANewAddress1
			,COANewAddress2
			,COANewCity
			,COANewState
			,COANewZip
			,MemberID
			,MemberCurrentHICN
			,GPSHouseholdID
			,MemberFirstName
			,MemberMiddleName
			,MemberLastName
			,MemberContractIDLkup
			,MemberPBPLkup
			,MemberLOBLkup
			,MemberVerifiedState
			,MemberVerifiedCountyCode
			,MemberDOB
			,MemberGenderLkup
			,EligGPSContractIDLkup
			,EligGPSPBPLkup
			,EligGPSSCCCode
			,EligGPSCurrentHICN
			,EligGPSInsuredPlanEffectiveDate
			,EligGPSInsuredPlanEffectiveDateId
			,EligGPSInsuredPlanTermDate
			,EligGPSInsuredPlanTermDateId
			,EligGPSLOBLkup
			,EligGPSMemberDOB
			,EligGPSMemberDOBId
			,EligGPSGenderLkup
			,EligMMRContractIDLkup
			,EligMMRPBPLkup
			,EligMMRSCCCode
			,EligMMRCurrentHICN
			,EligMMRPaymentAdjustmentStartDate
			,EligMMRPaymentAdjustmentStartDateId
			,EligMMRPaymentAdjustmentEndDate
			,EligMMRPaymentAdjustmentEndDateId
			,EligMMRPaymentMonth
			,EligMMRDOB
			,EligMMRDOBId
			,EligMMRGenderLkup
			,EligOOAFlagLkup
			,RPRRequestedEffectiveDate
			,RPRRequestedEffectiveDateId
			,RPRActionRequestedLkup
			,RPROtherActionRequested
			,RPRSupervisorOrRequesterRef
			,RPRReasonforRequest
			,RPRTaskPerformedLkup
			,RPROtherTaskPerformed
			,RPRCTMMember
			,RPRCTMNumber
			,RPREGHPMember
			,RPREmployerID
			,SCCRPRRequested
			,SCCRPRRequestedZip
			,SCCRPRRequstedSubmissionDate
			,SCCRPRRequstedSubmissionDateId
			,SCCRPREffectiveStartDate
			,SCCRPREffectiveStartDateId
			,SCCRPREffectiveEndDate
			,SCCRPREffectiveEndDateId
			,IsCasePended
			,PendedbyRef
			,UTCPendedOn
			,UTCPendedOnId
			,UTCPendedOnYear
			,UTCPendedOnMonth
			,UTCPendedOnDay
			,CSTPendedOn
			,CSTPendedOnId
			,CSTPendedOnYear
			,CSTPendedOnMonth
			,CSTPendedOnDay
			,IsCaseResolved
			,ResolvedByRef
			,UTCResolvedOn
			,UTCResolvedOnId
			,UTCResolvedOnYear
			,UTCResolvedOnMonth
			,UTCResolvedOnDay
			,CSTResolvedOn
			,CSTResolvedOnId
			,CSTResolvedOnYear
			,CSTResolvedOnMonth
			,CSTResolvedOnDay
			,PeerAuditCompletedDate
			,PeerAuditCompletedDateId
			,IsParentCase
			,IsChildCase
			,ParentQueueRef
			,IsActive
			,UTCCreatedOn
			,UTCCreatedOnId
			,UTCCreatedOnYear
			,UTCCreatedOnMonth
			,UTCCreatedOnDay
			,CSTCreatedOn
			,CSTCreatedOnId
			,CSTCreatedOnYear
			,CSTCreatedOnMonth
			,CSTCreatedOnDay
			,CreatedByRef
			,UTCLastUpdatedOn
			,UTCLastUpdatedOnId
			,UTCLastUpdatedOnYear
			,UTCLastUpdatedOnMonth
			,UTCLastUpdatedOnDay
			,CSTLastUpdatedOn
			,CSTLastUpdatedOnId
			,CSTLastUpdatedOnYear
			,CSTLastUpdatedOnMonth
			,CSTLastUpdatedOnDay
			,LastUpdatedByRef
			,GETUTCDATE()
			,CreatedByRef	
			,0		
			,MemberDOBId
			,TRCLkup
			,IsExtendTrackingRequired
			,MIIMReferenceId
			,IsMARxAddressCompleted
			,IsAddressScrubCompleted
			,RPRCategoryLkup
			,IsRestricted
			,OOALetterStatusLkup
			,CMSTransactionStatusLkup
			,IsNOTMacroProcessed
			,IsTRC155MacroProcessed
			,IsFTTMacroProcessed
			,NOTMacroStatusLkup
			,NOTMacroUpdatedOn
			,NOTMacroUpdatedByRef
			,TRC155MacroStatusLkup
			,TRC155MacroUpdatedOn
			,TRC155MacroUpdatedByRef
			,FTTMacroStatusLkup
			,FTTMacroUpdatedOn
			,FTTMacroUpdatedByRef
			,MemberMedicareId
			,ERNCaseID
			FROM INSERTED
GO