ALTER TABLE GEN_OSTActions ADD CONSTRAINT UQ_GEN_OSTActions_GEN_QueueRef UNIQUE (GEN_QueueRef)

ALTER TABLE GEN_EligibilityActions ADD CONSTRAINT UQ_GEN_EligibilityActions_GEN_QueueRef UNIQUE (GEN_QueueRef)

ALTER TABLE GEN_RPRActions ADD CONSTRAINT UQ_GEN_RPRActions_GEN_QueueRef UNIQUE (GEN_QueueRef)

ALTER TABLE ADM_UserMaster ADD CONSTRAINT UQ_ADM_UserMaster_MSID UNIQUE (MSID)

ALTER TABLE CMN_RecordsLocked ADD CONSTRAINT UQ_CMN_RecordsLocked_ScreenLkup_CaseId UNIQUE (ScreenLkup,CaseId)